FROM node:18-alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm install --omit=dev

# Bundle app source
COPY . .

# Expose port (Google Cloud Run expects port 8080 by default, but respects PORT env variable)
ENV PORT=8080
EXPOSE 8080

# Start server
CMD [ "node", "server.js" ]
